### ISSUE TITLE
invalid coords check - bug in core.py

### ISSUE THREAD

**Issue by spot2503** [bsmurphy/PyKrige#1]
Hi,
Thanks so much for your work.
I think on line 193 of core.py:
`if np.any(x == coords[0]) and np.any(y == coords[1]):`
the purpose is to check if there is a [x,y] that equals coords, however this line evaluates true if in the case of:
`x = [1, 2, 3]`
`y = [1, 2, 3]`
`coords = [1,2]`
however there is no `[x,y]` such that `coords == [1,2]`

I have gotten around this by using:
`bd = np.sqrt((x - coords[0])**2 + (y - coords[1])**2)`
`zero_value = np.any(bd <= 1e-8)`

I am unfamiliar with the internals of the algorithm so please let me know if my suspicion is incorrect.
Thanks

**Comment by bsmurphy** [comment]
Yep, you're correct. That's part of the process that ensures the kriged value at a data point converges to the actual data value, but at the moment it looks like I accidentally have things set up so that the code can get tricked into thinking we're trying to evaluate the kriging system at the data point when really we could just have two different grid points that separately have just an x-/y-coordinate in common with the data point. In the core module I don't think it's that big a deal, since that's currently only used for the statistics calculations. (I don't think it should throw an exception, but it might...) I'm pretty sure I have things set up the same way in the kriging classes though, and that would certainly be a problem. Thanks for pointing this out (and thanks for the interest in the code), I'll get to fixing that ASAP...

**Comment by bsmurphy** [comment]
This problem should be fixed in the package. Please let me know if you have any more problems with this bit, or anything else...
