### ISSUE TITLE
Is data problem or code?

### ISSUE THREAD

**Issue by jevy-wangfei** [bsmurphy/PyKrige#103]
I have a simple datasets and try using pykrige to grid it, but the result z value always the same.  I was blocked by this problem for a week, and try anything I could find online. 

I understand that this issue may not related with the PyKrige issue, but, please help me out if you know the reason. 

Very appreciate. 

## Data: 
Y,X,Value
-17.24638889,145.7744444,0
-17.18527778,145.7238889,0
-17.18527778,145.7238889,0
-17.13361,145.76444,0.3
-17.13305556,145.7625,0
-16.94555556,145.8288889,0
-17.10111,145.78944,0.5
-17.11583,145.83777,0
-17.13722,145.85722,0
-17.25861,145.92361,0.6
-17.29944,145.92833,0
-17.43666667,145.9436111,0
-17.38333,145.96666,0
-17.34888,145.87249,1
-17.3425,145.92499,0
-17.32472,145.95222,0
-17.11583,145.83777,0
-17.11722,145.85722,0
-17.15861,145.92361,0.6
-17.69944,145.92833,0
-17.83666667,145.9436111,0
-17.88333,145.96666,0
-17.84888,145.87249,0.3
-17.8425,145.92499,0
-17.32472,145.95222,0

## Code
from pykrige.ok import OrdinaryKriging
import pykrige.kriging_tools as kt
import numpy as np

data_array = np.genfromtxt('Station.csv', delimiter=',', skip_header=1)
print(type(data_array))
lon = data_array[:,1]
lat = data_array[:,0]
z = data_array[:,2]

grid_lon = np.linspace(144.0, 146.0, 99)
grid_lat = np.linspace(-18.0,-16.0, 99)

OK = OrdinaryKriging( lon, lat, z, variogram_model='linear', verbose=False,
                     enable_plotting=False, coordinates_type ="geographic")

z1, ss1 = OK.execute('grid', grid_lon, grid_lat)

print("Lon:    ",np.array_str(grid_lon[:], precision=9))
print("Lat:    ",np.array_str(grid_lat[:], precision=9))
print("Value:    ",np.array_str(z1[:,:], precision=9))

## output:
Value:     [[0.132 0.132 0.132 ... 0.132 0.132 0.132]
 [0.132 0.132 0.132 ... 0.132 0.132 0.132]
 [0.132 0.132 0.132 ... 0.132 0.132 0.132]
 ...
 [0.132 0.132 0.132 ... 0.132 0.132 0.132]
 [0.132 0.132 0.132 ... 0.132 0.132 0.132]
 [0.132 0.132 0.132 ... 0.132 0.132 0.132]]

**Comment by bsmurphy** [comment]
Looks like it's both a data problem and a code problem (kinda... well, a code use problem). 

First, your second and third data points are at the exact some spot (and have the same value), so that's going to produce a singular kriging system. Remove one of those lines.

Second, the actual problem you're having (output values all the same) is due to using a 'linear' variogram model and letting the code determine the "best" variogram model parameters. In this case, the values it's finding aren't good variogram model parameters. If you set ```enable_plotting=True```, you'll see the variogram is a flat line, so that's why you're getting all the same values in the output. Try this:

```python
OK = OrdinaryKriging(lon, lat, z, variogram_model='exponential', 
variogram_parameters=[0.08, 0.2, 0.], nlags=10, verbose=False, 
enable_plotting=True, coordinates_type ="geographic")
```

That should clear the degeneracy problem.

**Comment by jevy-wangfei** [comment]
Great, 

Your explanation is really very knowledgeable and solve my problem. 

Thank you very much. 


Please close this issue.
