### ISSUE TITLE
example err

### ISSUE THREAD

**Issue by hjiayz** [bsmurphy/PyKrige#11]
$ python2 Three-Dimensional-Kriging-Example.py
Traceback (most recent call last):
File "Three-Dimensional-Kriging-Example.py", line 35, in 
k3d, ss3d = uk3d.execute('grid', gridx, gridy, gridz, specified_drift_arrays=[xg, yg])
File "/usr/lib/python2.7/site-packages/pykrige/uk3d.py", line 752, in execute
raise ValueError("Dimensions of drift values array do not match specified grid dimensions.")
ValueError: Dimensions of drift values array do not match specified grid dimensions.

why?

**Comment by bsmurphy** [comment]
I think the documentation in the code got screwed up somehow, so let me try to explain what should be going on and maybe that will help. Since you're attempting to use 3D kriging, your system should involve three spatial coordinates (x, y, z) and the variable you're actually kriging is a fourth variable. With the specified drift term, you need to provide that fourth variable at every point (x, y, z) in your three-dimensional grid. Here's what the documentation says someplace (but not everywhere that it should say it, so understandable if you missed it...):

Array(s) must be the same dimension as the specified grid or have the same number of points as the specified points; i.e., the arrays either must be dim LxMxN, where L is the number of z grid-points, M is the number of y grid-points, and N is the number of x grid-points, or dim N, where N is the number of points at which to evaluate the kriging system.

I'm not sure what your xg and yg arrays actually look like, but since you're trying to do a gridded volume they should both be of shape [l, m, n]. Does that help?

**Comment by bsmurphy** [comment]
Oh I see where your example came from now... yeah that example in the README is wrong... sorry about that. It'd work for 2D kriging, but it won't work for 3D kriging for the reason I mentioned above.

**Comment by hjiayz** [comment]
good
