### ISSUE TITLE
3D universal kriging

### ISSUE THREAD

**Issue by foobarbecue** [bsmurphy/PyKrige#6]
Could you implement this? How much work would it take?

**Comment by bsmurphy** [comment]
It could certainly be implemented, I just haven't worked on it yet because I haven't thought enough about what drift terms to incorporate and how to incorporate them. A linear drift (or any polynomial drift) in the three spatial dimensions would be easy enough to incorporate, but extending other drift terms to 3D isn't as intuitive or straight forward. What drift terms would be useful for your applications?

**Comment by foobarbecue** [comment]
Well, I have point measurements of temperature spread out in 3D inside a cave chamber. There is a vertical temperature gradient and there may also be a radial temperature gradient due to a heat source in the middle of the floor of the chamber.

**Comment by bsmurphy** [comment]
I have an idea that I can try to implement that should allow for use of generic drift terms. It'll take me a little while to get to it (I'm already behind on some other work I've been trying to get to on the code), but in the mean time the linear drift in 3D should be easy to add. If you want, you can take a look at how I implemented the regional linear drift in 2D UK and add something similar for the three dimensions (x, y, z) in 3D. It really just amounts to adding the (x, y, z) coordinate values of data points to the kriging matrix (A) and the coordinate values of grid points to the RHS matrix (b). That should help out with your vertical (linear) temperature gradient.

**Comment by bsmurphy** [comment]
I've just uploaded a new version of the code to PyPI and here on GitHub that should help you out. Now you can use drift terms that you specify explicitly as well as drift terms that are defined by external functions that depend on the spatial variables. Let me know if you have any questions or run into any problems. (I've tested the code, but please let me know if any bugs turn up.)
