### ISSUE TITLE
New release on PyPI

### ISSUE THREAD

**Issue by jakirkham** [bsmurphy/PyKrige#60]
Seems there is [1.3.1]( https://github.com/bsmurphy/PyKrige/releases/tag/v1.3.1 ) tagged this past December. Would be nice to have it on PyPI where 1.3.0 is the latest.

**Comment by rth** [comment]
Thanks for checking this @jakirkham ! This situation is indeed not ideal, we should fix it.

Also @bsmurphy , maybe we could make the v1.4 release while we are at it? Since there were [quite a bit of changes in the last 6 months](https://github.com/bsmurphy/PyKrige/blob/master/release_notes.md#version-14) and the more in depth refactoring effort probably won't happen before some time. The only thing blocking is the doc generation #14 and CircleCi failures on master #53 (I will try to look into it this week).

**Comment by rth** [comment]
@bsmurphy Any chance you would have time to upload the v1.3.1 on PyPi? (Or if you send me the PyPi credentials I can do it..) Thanks! 

(this would also fix #70 etc).

**Comment by bsmurphy** [comment]
Alright, v1.3.1 is now on PyPI, v1.4.0 will be up there in the coming weeks once we address #14 and #53
